# Generated by Django 5.1.3 on 2024-11-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jersey',
            old_name='image_url',
            new_name='imageUrl',
        ),
    ]
