# Generated by Django 5.1.3 on 2024-11-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_image_url_jersey_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jersey',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
