# Generated by Django 5.1.3 on 2024-11-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_jersey_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jersey',
            name='description',
        ),
    ]
