# Generated by Django 5.1.3 on 2024-11-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_jersey_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jersey',
            name='category',
            field=models.CharField(choices=[('Retro', 'Camisetas Retro'), ('Camisetas2425', 'Camisetas 24/25'), ('Niños', 'Niños')], max_length=20),
        ),
    ]
