# Generated by Django 5.1.3 on 2024-11-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_jersey_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jersey',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
